name: club_plugin
version: '1.0'
main: me.callum.club_plugin.Club_plugin
api-version: '1.21'

commands:
  bal:
    description: fetches the balance of the player's wallet
  send:
    description: send tokens to another player or crypto wallet
  setToken:
    description: (OPERATOR ONLY) set the token address for the server currency
